name: "Release"

on:
  push:
    tags:
    - '**'

# Test Locally with:
# goreleaser build --skip-validate --snapshot

jobs:
  goreleaser:
    name: "Binary Release"
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'

      - name: Clean up dist directory
        run: rm -rf dist

      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: build --skip-validate

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --skip-validate --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-image:
    name: "Docker Release"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # all lowercase ghcr registry
      - run: |
         DOCKER_REGISTRY=`echo "ghcr.io/${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
         echo "DOCKER_REGISTRY=$DOCKER_REGISTRY" >> $GITHUB_ENV

         REPO_NAME=`echo "${{ github.repository }}" | awk -F'/' '{print $2}' | tr '[:upper:]' '[:lower:]'`
         echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      # build and publish package to ghcr (public) with codebase remaining private
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build and push Docker image
      - name: Build and push
        id: build_push_image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.DOCKER_REGISTRY }}/spawn:latest
            ${{ env.DOCKER_REGISTRY }}/spawn:${{ github.ref_name }}