name: check typos

on:
  pull_request:

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run codespell
        continue-on-error: true
        run: |
          # .codespellrc is used
          sudo apt-get install codespell -y
          codespell -w --config .codespellrc
          exit $?